version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
    - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "books"
      POSTGRES_USER: "books"
      POSTGRES_DB: "books"
    volumes:
    - /Users/peunov/Studies/volumes/pg:/var/lib/postgresql/data
